# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: courses.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import courses_types_pb2 as courses__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcourses.proto\x1a\x13\x63ourses_types.proto2\xbb\x01\n\rCourseService\x12Q\n\x0fGetCourseTopics\x12\x1f.courses.GetCourseTopicsRequest\x1a\x1d.courses.CourseTopicsResponse\x12W\n\x12\x43reateCourseTopics\x12\".courses.CreateCourseTopicsRequest\x1a\x1d.courses.CourseTopicsResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'courses_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COURSESERVICE._serialized_start=39
  _COURSESERVICE._serialized_end=226
# @@protoc_insertion_point(module_scope)
