# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import course_pb2 as course__pb2


class CourseServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCourseTopic = channel.unary_unary(
            '/course.CourseService/CreateCourseTopic',
            request_serializer=course__pb2.CreateCourseTopicRequest.SerializeToString,
            response_deserializer=course__pb2.CreateCourseTopicResponse.FromString,
        )


class CourseServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateCourseTopic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CourseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'CreateCourseTopic': grpc.unary_unary_rpc_method_handler(
            servicer.CreateCourseTopic,
            request_deserializer=course__pb2.CreateCourseTopicRequest.FromString,
            response_serializer=course__pb2.CreateCourseTopicResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'course.CourseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class CourseService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCourseTopic(request,
                          target,
                          options=(),
                          channel_credentials=None,
                          call_credentials=None,
                          insecure=False,
                          compression=None,
                          wait_for_ready=None,
                          timeout=None,
                          metadata=None):
        return grpc.experimental.unary_unary(request, target, '/course.CourseService/CreateCourseTopic',
                                             course__pb2.CreateCourseTopicRequest.SerializeToString,
                                             course__pb2.CreateCourseTopicResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
