# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import courses_types_pb2 as courses__types__pb2


class CourseServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCourseTopics = channel.unary_unary(
                '/CourseService/GetCourseTopics',
                request_serializer=courses__types__pb2.GetCourseTopicsRequest.SerializeToString,
                response_deserializer=courses__types__pb2.CourseTopicsResponse.FromString,
                )
        self.CreateCourseTopics = channel.unary_unary(
                '/CourseService/CreateCourseTopics',
                request_serializer=courses__types__pb2.CreateCourseTopicsRequest.SerializeToString,
                response_deserializer=courses__types__pb2.CourseTopicsResponse.FromString,
                )


class CourseServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCourseTopics(self, request, context):
        """rpc ListCourseTopic (ListCourseTopicRequest) returns (CourseTopicResponse);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCourseTopics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CourseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCourseTopics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCourseTopics,
                    request_deserializer=courses__types__pb2.GetCourseTopicsRequest.FromString,
                    response_serializer=courses__types__pb2.CourseTopicsResponse.SerializeToString,
            ),
            'CreateCourseTopics': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCourseTopics,
                    request_deserializer=courses__types__pb2.CreateCourseTopicsRequest.FromString,
                    response_serializer=courses__types__pb2.CourseTopicsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CourseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CourseService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCourseTopics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CourseService/GetCourseTopics',
            courses__types__pb2.GetCourseTopicsRequest.SerializeToString,
            courses__types__pb2.CourseTopicsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateCourseTopics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CourseService/CreateCourseTopics',
            courses__types__pb2.CreateCourseTopicsRequest.SerializeToString,
            courses__types__pb2.CourseTopicsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
