"""init

Revision ID: 99c910f38e9d
Revises: 
Create Date: 2023-02-02 12:07:29.490391

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
import app # custom added
from typing import Text # custom added


# revision identifiers, used by Alembic.
revision = '99c910f38e9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Locales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_Locales_id'), 'Locales', ['id'], unique=False)
    op.create_table('Media',
    sa.Column('title', app.models.base_model.SaTranslationField(astext_type=Text()), nullable=True),
    sa.Column('description', app.models.base_model.SaTranslationField(astext_type=Text()), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Media_id'), 'Media', ['id'], unique=False)
    op.create_table('Permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('permission_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Permissions_id'), 'Permissions', ['id'], unique=False)
    op.create_table('Roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('role_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Roles_id'), 'Roles', ['id'], unique=False)
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mobile', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Users_id'), 'Users', ['id'], unique=False)
    op.create_table('CourseTopics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('locale_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['locale_id'], ['Locales.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['CourseTopics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CourseTopics_id'), 'CourseTopics', ['id'], unique=False)
    op.create_table('FileMedia',
    sa.Column('file_format', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('media_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['Media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_FileMedia_id'), 'FileMedia', ['id'], unique=False)
    op.create_table('ImageMedia',
    sa.Column('file_format', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('media_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['Media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ImageMedia_id'), 'ImageMedia', ['id'], unique=False)
    op.create_table('RolePermissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['Permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['Roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_RolePermissions_id'), 'RolePermissions', ['id'], unique=False)
    op.create_table('UserRoles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['Roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_UserRoles_id'), 'UserRoles', ['id'], unique=False)
    op.create_table('CourseCategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('main_course_topic_id', sa.Integer(), nullable=True),
    sa.Column('icon_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('locale_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['icon_id'], ['ImageMedia.id'], ),
    sa.ForeignKeyConstraint(['locale_id'], ['Locales.id'], ),
    sa.ForeignKeyConstraint(['main_course_topic_id'], ['CourseTopics.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['CourseTopics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CourseCategories_id'), 'CourseCategories', ['id'], unique=False)
    op.create_table('Courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('locale_id', sa.Integer(), nullable=True),
    sa.Column('photo_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('trailer_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['locale_id'], ['Locales.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['CourseTopics.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['ImageMedia.id'], ),
    sa.ForeignKeyConstraint(['trailer_id'], ['FileMedia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Courses_id'), 'Courses', ['id'], unique=False)
    op.create_table('CategoriesCourses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['CourseCategories.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['Courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CategoriesCourses_id'), 'CategoriesCourses', ['id'], unique=False)
    op.create_table('CoursePrices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('percent', sa.Float(), nullable=True),
    sa.Column('percent_price', sa.Float(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['Courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CoursePrices_id'), 'CoursePrices', ['id'], unique=False)
    op.create_table('UserCoursePurchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('course_price_id', sa.Integer(), nullable=True),
    sa.Column('paid_percent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['Courses.id'], ),
    sa.ForeignKeyConstraint(['course_price_id'], ['CoursePrices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_UserCoursePurchases_id'), 'UserCoursePurchases', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_UserCoursePurchases_id'), table_name='UserCoursePurchases')
    op.drop_table('UserCoursePurchases')
    op.drop_index(op.f('ix_CoursePrices_id'), table_name='CoursePrices')
    op.drop_table('CoursePrices')
    op.drop_index(op.f('ix_CategoriesCourses_id'), table_name='CategoriesCourses')
    op.drop_table('CategoriesCourses')
    op.drop_index(op.f('ix_Courses_id'), table_name='Courses')
    op.drop_table('Courses')
    op.drop_index(op.f('ix_CourseCategories_id'), table_name='CourseCategories')
    op.drop_table('CourseCategories')
    op.drop_index(op.f('ix_UserRoles_id'), table_name='UserRoles')
    op.drop_table('UserRoles')
    op.drop_index(op.f('ix_RolePermissions_id'), table_name='RolePermissions')
    op.drop_table('RolePermissions')
    op.drop_index(op.f('ix_ImageMedia_id'), table_name='ImageMedia')
    op.drop_table('ImageMedia')
    op.drop_index(op.f('ix_FileMedia_id'), table_name='FileMedia')
    op.drop_table('FileMedia')
    op.drop_index(op.f('ix_CourseTopics_id'), table_name='CourseTopics')
    op.drop_table('CourseTopics')
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_Roles_id'), table_name='Roles')
    op.drop_table('Roles')
    op.drop_index(op.f('ix_Permissions_id'), table_name='Permissions')
    op.drop_table('Permissions')
    op.drop_index(op.f('ix_Media_id'), table_name='Media')
    op.drop_table('Media')
    op.drop_index(op.f('ix_Locales_id'), table_name='Locales')
    op.drop_table('Locales')
    # ### end Alembic commands ###
